require("osagie.core.options")
require("osagie.core.keymaps")
require("osagie.core.autocommands")

require("osagie.plugins")
require("osagie.plugins.lsp")
require("osagie.plugins.cmp")
require("osagie.plugins.treesitter")
require("osagie.plugins.telescope")
require("osagie.plugins.theme")
require("osagie.plugins.undotree")
